name: secragrgws
favicon: null
layout_spectrum: 0.21042505046352744
typography_spectrum: 0.8682483718730509
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.43150354200042784
  lightness: 0.24329456058330834
  saturation: 0.5677004309836775
  rhythmicContrast: 0.48136132466606796
purpose: []
